# Generated by Django 6.0.4 on 2026-04-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(
                blank=True,
                help_text="ID чата в Telegram для отправки уведомлений",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Telegram Chat ID",
            ),
        ),
    ]
