# Generated by Django 6.0.4 on 2026-04-22 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Сюда можно добавить только приятную привычку",
                limit_choices_to={"is_pleasant": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependent_habits",
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
    ]
