# Generated by Django 6.0.4 on 2026-04-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_related_habit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={
                "ordering": ["-id"],
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
